name: Build Backend

# trigger condition for the action
on:
  push:
    branches: ["*"]
  pull_request:
    branches: [CI-CD]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  prepare:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: install dependencies
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - name: publish dist folder as an artifact
      uses: actions/upload-artifact@v3
      with:
          name: dist_dir
          path: dist