name: Deploy on Heroku

# trigger condition for the action
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
